spring:
  datasource:
    password: ${DATABASE_PASSWORD:root}
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/spring-security-jwt-test?createDatabaseIfNotExist=TRUE}
    username: ${DATABASE_USERNAME:root}

  jpa:
    hibernate:
      ddl-auto: update
 
  flyway:
    enabled: true

